:command BClosePreviews call bufutils#BClosePreviews() 
:command BCloseAll call bufutils#BCloseAll() 
:command BCloseOther call bufutils#BCloseOther()
:command BCloseLeft call bufutils#BCloseLeft()
:command BCloseRight call bufutils#BCloseRight()
